name: Build

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pylint
        python3 -m pip install build
        python3 -m pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: python3 -m pylint --recursive yes .

    - name: Run unittests 
      run: echo "unittests TODO"

    - name: Build package
      run: python3 -m build

    - name: Upload wheel file
      uses: actions/upload-artifact@v3
      with:
        name: pocket_ic_${{ github.sha }}.whl
        path: dist/*.whl

    - name: Upload sources
      uses: actions/upload-artifact@v3
      with:
        name: pocket_ic_${{ github.sha }}.tar.gz
        path: dist/*.tar.gz

    - name: Run integration tests  # from examples directory
      run: echo "integration tests TODO"
  
  release: 
    needs: build
    if: ${{ github.event_name == 'release' }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/download-artifact@v3
      with: 
        name: pocket_ic_${{ github.sha }}.whl
        
    - uses: actions/download-artifact@v3
      with: 
        name: pocket_ic_${{ github.sha }}.tar.gz
      
    - name: upload artifacts to release page
      uses: softprops/action-gh-release@master
      with: 
        files: |
          pocket_ic-0.0.0-py3-none-any.whl
          pocket_ic-0.0.0.tar.gz
      
    
  publish: 
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - run: echo "publishing TODO"
