name: Build

on: [push, pull_request, release]

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22

    - name: Build package
      id: release-build
      run: |
        dist=$(nix build --no-link --print-out-paths --print-build-logs .#default.dist)
        echo "dist=$dist" >> $GITHUB_OUTPUT

    - name: Test package
      run: nix flake check --print-build-logs

    - if: matrix.os == 'ubuntu-latest'
      name: Upload wheel file
      uses: actions/upload-artifact@v3
      with:
        name: pocket_ic_${{ github.sha }}.whl
        path: ${{ steps.release-build.outputs.dist }}/*.whl

  release:
    needs: build
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with: 
        name: pocket_ic_${{ github.sha }}.whl

    - name: Set tag
        id: set_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Set artifact name
        id: set_name
        run: echo "artifact_name=pocket_ic-${{ steps.set_tag.outputs.tag }}-py3-none-any.whl" >> $GITHUB_OUTPUT

    - name: ls
      run: echo `ls -la `

    - name: rename artifact
      run: mv pocket_ic*.whl ${{ steps.set_name.outputs.artifact_name }}

    - name: upload artifacts to release page
      uses: softprops/action-gh-release@master
      with:
        files: |
          ${{ steps.set_name.outputs.artifact_name }}
