name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          # pip install -r requirements.txt
      - name: Build package
        run: python -m build
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.python-version }}
          path: dist/*
        
